name: CI
on: [ push, pull_request ]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
  test:
    strategy:
      matrix:
        os: [
          macos-11,
          macos-12,
          macos-13,
        ]
        image: [
          x86_64,
          x86_64-slim,
          x86_64-xcode_cli,
          x86_64-xcode_cli-slim
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: brew install crane
      - run: |
          echo building jail with ${{ matrix.image }}
          case "${{ matrix.image }}" in
            "x86_64")
              export mkjail_files="macosjail/mkjail.files.x86_64_full"
              ;;
            "x86_64-slim")
              export mkjail_files="macosjail/mkjail.files.x86_64_slim"
              ;;
            "x86_64-xcode_cli")
              export mkjail_files="macosjail/mkjail.files.x86_64_full,macosjail/mkjail.files.xcode-command-line-tools"
              ;;
            "x86_64-xcode_cli-slim")
              export mkjail_files="macosjail/mkjail.files.x86_64_slim,macosjail/mkjail.files.xcode-command-line-tools"
              ;;
            *)
              echo "Unknown image: ${{ matrix.image }}"
              ;;
          esac
          echo "building jail with $mkjail_files"
          sudo python3 -m macosjail jail -f macosjail/mkjail.files.base,$mkjail_files
